package my.android.app;
/*
 * Copyright (C) 2016 Orange
 * Authors: Christophe Maldivi
 *
 * This software is the confidential and proprietary information of Orange.
 * You shall not disclose such confidential information and shall use it only
 * in accordance with the terms of the license agreement you entered into
 * with Orange.
 */

public class Cartoon {

  public static final String[] CHARACTERS =  {
    "Akéla",
    "Alçmène & Amphitryon",
    "Anästâsià",
    "Anita",
    "Bagheera",
    "Baloo",
    "Bashful",
    "Brunô",
    "Captain Hook",
    "Cinderella",
    "Colonel Hathi",
    "Colonel",
    "Cruella de Vil",
    "Doc",
    "Dopey",
    "Drizella",
    "Eeyore",
    "Fairy Godmother",
    "Friar Tuck",
    "George Darling",
    "Grumpy",
    "Hades",
    "Happy",
    "Hera",
    "Hercules",
    "Hermes",
    "Horace",
    "Jaq",
    "Jasper ",
    "John",
    "Kaa",
    "Kanga & Roo",
    "Kiara",
    "King Louie",
    "King of Duke ",
    "King Richard",
    "Kovu",
    "Lady Tremaine",
    "Little John",
    "Lost boys ",
    "Lumpy",
    "Ma",
    "Maid Marian",
    "Major",
    "Mary Darling",
    "Megara",
    "Michael",
    "Mowgli",
    "Mufasa",
    "Nala",
    "Nana",
    "Nessus",
    "Nuka",
    "Octavius (Gus)",
    "Pain & Panic",
    "Pegasus",
    "Perdita",
    "Peter Pan",
    "Phil",
    "Piglet",
    "Prince Charming",
    "Prince John",
    "Queen",
    "Rabbit",
    "Rafiki",
    "Robin Hood",
    "Roger",
    "Sarabi",
    "Sarafina",
    "Scar",
    "Shanti",
    "Shenzi, Banzai and Ed",
    "Shere Khan ",
    "Sheriff of Nottingham",
    "Simba",
    "Sir Hiss",
    "Skippy ",
    "Sleepy",
    "Smee",
    "Sneezy",
    "Snow White ",
    "The Crocodile",
    "The Lost Boys",
    "The Magic Mirror",
    "The Prince",
    "Tibbs",
    "Tiger Lily",
    "Tigger",
    "Timon and Pumbaa",
    "Tinker Bell",
    "Trigger & Nutsey",
    "Uncle Max ",
    "Vitani",
    "Wendy",
    "Winnie the Pooh",
    "Zazu",
    "Zeus",
    "Zira"
  };

}
